### ISSUE TITLE
Timer library?

### ISSUE THREAD

**Issue by kberzinch** [swampbotics/core#11]
`LCD.h` has its own code for making the timer in the top-right pretty. Would something like that be generally applicable for other uses?

Getting milliseconds since a time is trivial; the other methods make it easy to get seconds and minutes, especially for display where you want to subtract higher units.

**Comment by MureedSultan** [comment]
Maybe

**Comment by kberzinch** [comment]
I'm going to leave it out then. If the need arises you can pull the basic stuff from `LCD.h`.
