### ISSUE TITLE
Use ROBOTC built-in flags for left and right drive train motors

### ISSUE THREAD

**Issue by kberzinch** [swampbotics/core#3]
It's possible to register a motor as being on one or the other side of the drive train in Motors and Sensors setup ([link](http://help.robotc.net/WebHelpVEX/index.htm#Resources/topics/VEX_IQ/ROBOTC/Drive_Train/getMotorsWithDriveSideType.htm)) - I think that would be a better way to work with `core` than requiring the motors to be named something specific and using the slave functionality.

@MureedSultan thoughts?

**Comment by kberzinch** [comment]
Note that this would only apply for inline drives - for holonomic/mecanum `core` needs to know exact location of each motor anyway.

**Comment by MureedSultan** [comment]
Works for me.

**Comment by kberzinch** [comment]
Reopening as this is something I have to implement.
