### ISSUE TITLE
Any interest in datalogging?

### ISSUE THREAD

**Issue by kberzinch** [swampbotics/core#6]
For a while v3 would dump encoder values to the debug stream while driving. ROBOTC now includes [datalogging functionality](http://help.robotc.net/WebHelpVEX/index.htm#Resources/topics/VEX_Cortex/ROBOTC/Datalogging/datalogAddValue.htm) that does something similar in a nicer way. Is that something you would be interested in?

**Comment by MureedSultan** [comment]
Can't think of a reason for this season.
